group class thing
ZantixGroup/active-fitness-fe pull request #16
Opened 2024-04-17 23:36 UTC by borderss

group class thing

2024-04-17 23:39 UTC, Fleksis requested changes

2024-04-17 23:39 UTC, Fleksis commented on src/Admin/components/form_actions/RedirectAction.vue
> +      console.log(this.route);
noņemt

2024-04-17 23:39 UTC, Fleksis commented on src/Admin/views/classes/AttendeeListView.vue
> +            console.log(data);
Noņemt

2024-04-17 23:39 UTC, Fleksis commented on src/Admin/views/classes/AttendeeListView.vue
> +            console.log(data);
Noņemt

2024-04-18 14:10 UTC, borderss reviewed
asd

2024-04-18 14:10 UTC, borderss commented on src/Admin/views/classes/AttendeeListView.vue
> +            console.log(data.user.id)
```suggestion
```

2024-04-20 23:52 UTC, merged